### ISSUE TITLE
[Feature Request] Add configuration files for Caddy

### ISSUE THREAD

**Issue by ericswpark** [linuxserver/fail2ban-confs#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Please add configuration files for Caddy! It's a really good web server that I use to reverse proxy to services, but there aren't any filter or jail configuration files for it yet.

**Comment by Roxedus** [comment]
Considering no one on the team uses Caddy, this would have to be a contribution from someone who uses it.

Closing this as it's not something we are able to provide ourselves, but we are of course accepting pull requests for this.
